[build]
  base = "frontend"
  publish = "out"
  command = "npm install && npm run build"

[build.environment]
  NODE_VERSION = "18"
  NEXT_PUBLIC_BACKEND_URL = "https://socialauth-1tz8.onrender.com"
  NODE_ENV = "production"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
