[build]
  base = "frontend"
  publish = "frontend/.next"
  command = "npm ci && npm run build"

[build.environment]
  NODE_VERSION = "18"
  NEXT_PUBLIC_BACKEND_URL = "https://socialauth-1tz8.onrender.com"
  NODE_ENV = "production"

# Enable Next.js SSR
[[plugins]]
  package = "@netlify/plugin-nextjs"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
